phrase = "Learning string"
print("Learning\nstrin")
print("Learning \"string\"")
print(phrase + "is cool")
print(phrase.lower())
print(phrase.upper())
print(phrase.isupper())
print(phrase.upper().isupper())
print(len(phrase))
print([0])
print(phrase.index("str"))
print(phrase.replace("Learning", "Studying"))